
local SPAWN_TIME_MULT = 1.8

local def = {
	humanName = "Drain Circling",
	prevLevel = "level1",
	gravity = 80,
	starCount = 2500,
	asteroidSpawn = {
		{
			timeMin = 1.5 * SPAWN_TIME_MULT,
			timeRand = 0.8 * SPAWN_TIME_MULT,
			speedMin = 0,
			speedMax = 10,
			orbitMult = 0.8,
			orbitMultRand = 0.1,
			orbitMultBothDirections = 0,
			topBotChance = 1,
			avoidOrbitOverWrap = true,
			forceTop = true,
			spawnRange = 0.3,
			spawnOffset = -0.15,
			typeName = {"asteroid_med", "asteroid_med", "asteroid_med", "asteroid_big"},
		},
		{
			timeMin = 1.5 * SPAWN_TIME_MULT,
			timeRand = 0.8 * SPAWN_TIME_MULT,
			speedMin = 0,
			speedMax = 10,
			orbitMult = 0.8,
			orbitMultRand = 0.1,
			orbitMultBothDirections = 0,
			topBotChance = 1,
			avoidOrbitOverWrap = true,
			forceBottom = true,
			spawnRange = 0.3,
			spawnOffset = 0.15,
			typeName = {"asteroid_med", "asteroid_med", "asteroid_med", "asteroid_big"},
		},
		{
			timeMin = 3 * SPAWN_TIME_MULT,
			timeRand = 1 * SPAWN_TIME_MULT,
			speedMin = 0,
			speedMax = 10,
			orbitMult = 0.4,
			orbitMultRand = 0.1,
			orbitMultBothDirections = 0,
			avoidOrbitOverWrap = true,
			forceLeft = true,
			spawnRange = 0.3,
			spawnOffset = -0.15,
			typeName = {"asteroid_med", "asteroid_med", "asteroid_med", "asteroid_big"},
		},
		{
			timeMin = 3 * SPAWN_TIME_MULT,
			timeRand = 1 * SPAWN_TIME_MULT,
			speedMin = 0,
			speedMax = 10,
			orbitMult = 0.4,
			orbitMultRand = 0.1,
			orbitMultBothDirections = 0,
			avoidOrbitOverWrap = true,
			forceRight = true,
			spawnRange = 0.3,
			spawnOffset = 0.15,
			typeName = {"asteroid_med", "asteroid_med", "asteroid_med", "asteroid_big"},
		},
	},
	planets = {
		{
			pos = {-1000, 0},
			radius = 95,
			density = 150,
			age = "stone",
			maxAge = "space",
			ageSpeed = 1/15,
			guySpeed = 1/6,
			guyGap = 8,
			guyAgeBoost = 1.5,
			fillLastAge = false,
		},
	},
	sun = {
		alignX = 0.5,
		alignY = 0.5,
		radius = 200,
		image = "sun",
	},
	asteroids = {
	},
	goal = {
	},
	player = {
		pos = {-300, -500},
		orbitMult = -0.95,
	},
}

return def
